type Essay {
  # The unique identifier of the essay
  id: ID!
  # A markdown content of the essay (without the main title)
  content: String!
  # The title of the essay
  title: String!
  # A ISO-8601 compatible date string
  date: String!
  # A description of the post limited to 140 characters
  description: String
  # The essay file name
  slug: String
  # The list of tag assigned to the essay
  tags: [String]
  # The URL of the cover image for the essay
  cover: String
  # The canonical URL associated to the essay
  canonicalUrl: String
  # If the essay is published it will be used in the list of essays
  published: Boolean
}

input PublishInput {
  # A markdown content of the essay (without the main title)
  content: String!
  # The title of the essay
  title: String!
  # The essay file name
  slug: String!
  # A description of the post limited to 140 characters
  description: String!
  # The list of tag assigned to the essay
  tags: [String!]
  # The URL of the cover image for the essay
  cover: String
  # The canonical URL associated to the essay
  canonicalUrl: String
}
